
services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

volumes:
  db_data:
